2025-10-06 14:30:49,422 -  INFO - info message
2025-10-06 14:30:49,422 -  WARNING - warning message
2025-10-06 14:30:49,422 -  ERROR - error message
2025-10-06 14:30:49,422 -  CRITICAL - critical message
2025-10-06 14:55:27,771 -  INFO - info message
2025-10-06 14:55:27,771 -  WARNING - warning message
2025-10-06 14:55:27,771 -  ERROR - error message
2025-10-06 14:55:27,771 -  CRITICAL - critical message
2025-10-06 15:38:08,815 - ERROR - Invalid marks error occurred
Traceback (most recent call last):
  File "C:\Users\user2\PycharmProjects\PythonProject\Training\5-oct\excep.py", line 20, in <module>
    check_marks(120)  # This will raise
    ~~~~~~~~~~~^^^^^
  File "C:\Users\user2\PycharmProjects\PythonProject\Training\5-oct\excep.py", line 17, in check_marks
    raise InvalidMarksError(f"Marks must be between 0 and 100. You passed: {marks}")
InvalidMarksError: Marks must be between 0 and 100. You passed: 120
